name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v26

      - run: nix-shell --run "python test.py chromium"
      - run: nix-shell --run "python test.py firefox"
      - run: nix-shell --run "ldd \${PLAYWRIGHT_BROWSERS_PATH}/webkit-1983/minibrowser-gtk/bin/MiniBrowser"
      - run: nix-shell --run "python test.py webkit"
